server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Angular routing — refresh on any URL works
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy all API calls to Spring Boot backend
    location ~ ^/(user|category|product|bill|dashboard|password)/ {
        proxy_pass       http://cafe-app-backend:8081;
        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        client_max_body_size 10M;
    }
}
